# Minecraft and Yarn versions
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.19.5

# Fabric API
fabric_version=0.141.6+1.21.11

# GUI
modmenu_version=16.0.1
yacl_version=3.8.1+1.21.11-fabric

# Mоd information
mod_version=1.2.0
maven_group=ru.uggtiu
archives_base_name=locatorbarextended
org.gradle.jvmargs=-Xmx3G -XX:+UseG1GC

